### PR TITLE
Remove unnecessary bin path for Grunt to run on Windows

### PR DESCRIPTION
**Pull request by ZitRos**
This tiny PR fixes build on Windows.

On Windows, `npm install` could not finish the initialization because of `postinstall` script:

```bash
...
> multisigweb@1.3.6 postinstall C:\ZitRo\Projects\gnosis-multisig\project\MultiSigWallet\dapp
> ./node_modules/grunt/bin/grunt ngtemplates

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! multisigweb@1.3.6 postinstall: `./node_modules/grunt/bin/grunt ngtemplates`
npm ERR! Exit status 1
...
```

In npm it is not required to write the full path to Grunt like `./node_modules/grunt/bin/grunt`, you can just write `grunt` and NPM will resolve locally installed Grunt.

### CODE REVIEW

**Comment by giacomolicari** [comment]
Hi @ZitRos , thank you for your PR, please use local node_modules instead of global ones.

**Comment by ZitRos** [comment]
@giacomolicari it doesn't use global `node_modules`! NPM scripts resolve `grunt` to **locally** installed grunt:

image

Hence, this PR just add support for builds on Windows, because `./node_modules/grunt/bin/grunt` **isn't valid for Windows**.

Please merge! 😄 My next PR will add addresses select support for Trezor hardware wallet.

**Comment by giacomolicari** [comment]
Thanks @ZitRos , will be included in the next release.

**Comment by ZitRos** [comment]
Thanks @giacomolicari!

**Pull request merged**
