### PR TITLE
Update solidity version to the latest provided by truffle

### PR DESCRIPTION
**Pull request by prestonvanloon**
Solves the following error: 

```
SyntaxError: Source file requires different compiler version (current compiler is 0.4.19+commit.c4cbbb05.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.4.15;
```

Truffle version:

```
Truffle v4.1.3 (core: 4.1.3)
Solidity v0.4.19 (solc-js)
```

### CODE REVIEW

**Comment by prestonvanloon** [comment]
Oops, I need to update the version truffle travis runs.

**Comment by elenadimitrova** [comment]
Truffle just went up a version with solc to 0.4.21 perhaps just go straight to that?

**Comment by prestonvanloon** [comment]
@elenadimitrova Done!

**Comment by prestonvanloon** [comment]
Looks like this won't be merged any time soon...

**Pull request closed without merging**
